name: five
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  cupertino_icons: ^1.0.8
  go_router: ^13.0.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: 5.6.8
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  permission_handler: ^11.0.0
  firebase_storage: ^12.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/circular-std-medium-500.ttf

    - family: Caros
      fonts:
        - asset: assets/fonts/cretype-Caros-Black.otf
          weight: 900
        - asset: assets/fonts/cretype-Caros-Medium.otf
          weight: 500
        - asset: assets/fonts/cretype-Caros.otf
          weight: 400
        - asset: assets/fonts/cretype-Caros-Bold.otf
          weight: 700
