// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsTaU_PCVoUgaqo20Vqmi6p7AdjuzuMKA',
    appId: '1:216652396183:web:c11d4c5914ff5f16b89bd2',
    messagingSenderId: '216652396183',
    projectId: 'chatme-ed761',
    authDomain: 'chatme-ed761.firebaseapp.com',
    storageBucket: 'chatme-ed761.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEDvgeFw7VdbeWKjfrQSPMd5sFwuukrtU',
    appId: '1:216652396183:android:5926199e851aee53b89bd2',
    messagingSenderId: '216652396183',
    projectId: 'chatme-ed761',
    storageBucket: 'chatme-ed761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChNuRW7gUFrxP5GVlzvjarrQLSsMbopMc',
    appId: '1:216652396183:ios:051a064513064a10b89bd2',
    messagingSenderId: '216652396183',
    projectId: 'chatme-ed761',
    storageBucket: 'chatme-ed761.firebasestorage.app',
    iosBundleId: 'com.example.five',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChNuRW7gUFrxP5GVlzvjarrQLSsMbopMc',
    appId: '1:216652396183:ios:051a064513064a10b89bd2',
    messagingSenderId: '216652396183',
    projectId: 'chatme-ed761',
    storageBucket: 'chatme-ed761.firebasestorage.app',
    iosBundleId: 'com.example.five',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsTaU_PCVoUgaqo20Vqmi6p7AdjuzuMKA',
    appId: '1:216652396183:web:519ef1ef17a111fdb89bd2',
    messagingSenderId: '216652396183',
    projectId: 'chatme-ed761',
    authDomain: 'chatme-ed761.firebaseapp.com',
    storageBucket: 'chatme-ed761.firebasestorage.app',
  );

}